import { Toaster } from '@/components/ui/sonner';
import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        {children}
        <Toaster />
    </>
  )
}
